spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 클라이언트 ID
            client-secret: 암호키
            scope: profile,email
          naver:
            client-id: 클라이언트 ID
            client-secret: 암호키
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name,email,profile_image
            client-name: Naver
          facebook:
            client-id: 클라이언트 ID
            client-secret: 암호키
          kakao:
            authorization-grant-type: authorization_code
            client-id: 클라이언트 ID
            client-secret: 암호키
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            scope: profile
            client-authentication-method: POST
            client-name: Kakao
          github:
            client-id: 클라이언트 ID
            client-secret: 암호키
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id