spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 52484869560-q3eboao3d6bjr8tksm1rlp6tlr5qaf6l.apps.googleusercontent.com
            client-secret: WYuo6vAv5anUu3n5XMUuHF8Q
            scope:
              - profile
              - email
          naver:
            client-id: LYOeWyeVNRLDCCvmXMWd
            client-secret: c5RmW_IUZc
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
              - profile_image
            client-name: Naver
          facebook:
            client-id: 252477422528968
            client-secret: fec6cb8596494ccfffafdd787ce96ea2
            scope:
              - email
              - public_profile
          kakao:
            authorization-grant-type: authorization_code
            client-id: 03f9392c67ca0ac1ca399f82106fbfed
            client-secret: 6ZQn8GhOtoZzeDbA6L9A85hH2NyQoz8s
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - profile
              - email
            client-authentication-method: POST
            client-name: Kakao
          github:
            client-id: 94f534f59e3a99d827cb
            client-secret: 7bd068f5ad32f8502fd55cee9dd84d110f10a29d
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id